version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: fullstack-app-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: fullstack-app-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: fullstack-app-frontend
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:8000/items/
    depends_on:
      - backend
    entrypoint: ["/docker-entrypoint.sh"]

volumes:
  mongo_data:
